frate/config/routes.rb
Rails.application.routes.draw do
  post '/users/:id/reviews', to: 'reviews#create'
  resources :users do
    resources :reviews
    resources :matches
  end

  delete 'analytics/index', to: 'sessions#destroy'
  post '/users/:id', to: 'users#remove_friend'
  get '/users/:id', to: 'users#remove_friend'

  patch '/add_friend_profile/:id', to: 'users#add_friend_profile'

  get '/remove_friend/:id', to: 'users#delete_friendship'
  patch '/remove_friend/:id', to: 'users#delete_friendship'

  resources :reviews
  resources :sessions
  resources :analytics

  get 'analytics/index'
  resources :matches
  resources :homes

  get '/homes/homepage', to: 'homes#index'

  get '/users/:id/reviews', to: 'reviews#index'
  
  patch '/add_friend/:id', to: 'users#add_friend' 
  

  get 'login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get 'authorized', to: 'sessions#page_requires_login'

  resources :conversations do
    resources :messages
  end


end

frate/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

frate/app/models/match.rb
class Match < ApplicationRecord
    belongs_to :friend, class_name: 'User'
    belongs_to :friende, class_name: 'User'
end

frate/app/models/review.rb
class Review < ApplicationRecord
    belongs_to :reviewer, class_name: 'User'
    belongs_to :reviewee, class_name: 'User'
    #reviewee is unique relative to scope of reviewer


    
    def not_reviewed
        @reviewing = self.reviewees
        @users = User.all
        @not_reviewing = @users - @reviewing
    end


end

frate/app/models/user.rb
class User < ApplicationRecord
    has_many :friended_users, foreign_key: :friend_id, class_name: 'Match'
    has_many :friendes, through: :friended_users
    has_many :friending_users, foreign_key: :friende_id, class_name: 'Match'
    has_many :friends, through: :friending_users


    has_many :reviewed_users, foreign_key: :reviewer_id, class_name: 'Review'
    has_many :reviewees, through: :reviewed_users
    has_many :reviewing_users, foreign_key: :reviewee_id, class_name: 'Review'
    has_many :reviews, through: :reviewing_users, source: :reviewee

    has_secure_password
    
    has_many :reviews
    has_one_attached :avatar
    validates :name, presence: true, uniqueness: true
  

    def not_friends
        @friending = self.friendes
        @users = User.all
        @not_friending = @users - @friending
    end

    def self.users_count
        User.all.count
    end

    def self.average_age
        average = 0.0
        User.all.each do |t|
            average += t.age
           
            end
        (average / User.all.count).round
    end

   


    def not_reviewed
        @reviewing = self.reviewees
        @users = User.all
        @not_reviewing = @users - @reviewing
    end



end

frate/app/controllers/analytics_controller.rb
class AnalyticsController < ApplicationController
  before_action :authorized, except: [:new, :create]
  before_action :current_user, except: [:new, :create]
  
  def index
  end
end

frate/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    helper_method :current_user

    def logged_in?
        !!current_user
    end

    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end

   def current_page
    @current_page = user_path()
   end

    def authorized
        redirect_to '/homes/home_page' if !logged_in?
    end


end

frate/app/controllers/homes_controller.rb
class HomesController < ApplicationController

def index
end
  
def home_page
end

def show
end

end

frate/app/controllers/matches_controller.rb
class MatchesController < ApplicationController
end

frate/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    def index  
        @reviews = Review.all
        @user = User.find(params[:user_id])  
    end

    def show # a single review? How/why do we want this
        @review = Review.find(params[:id])
    end

    def new
        @review = Review.new
    end

    #save with strong params ?
    def create 
        # binding.pry
        reviewer_id = session[:user_id]
        reviewee_id = params[:id]
        content = params[:content]
        @review = Review.create!(reviewer_id: reviewer_id,
        reviewee_id: reviewee_id, content: content)
        
        if @review.save
            redirect_to "/users/#{@review.reviewee_id}/reviews"
        else 
            redirect_to '/users'
        end
    end


    private

    def review_params
        #params.require(:review).permit(:content, :reviewee_id)
    end
    
end

frate/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
   before_action :authorized, except: [:new, :create]
   before_action :current_user, except: [:new, :create]

    def new
    end

    def create
      @user = User.find_by(name: params[:name])
      if @user && @user.authenticate(params[:password])
         session[:user_id] = @user.id
         redirect_to @user
      else
         if @user == nil
            flash[:notice] = 'User not found.'
         else
            flash[:notice] = "Wrong password."
         end
         redirect_to '/login'
      end
   end

   def destroy
      session[:user_id] = nil
      redirect_to '/homes/home_page'
   end

  end

frate/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorized, except: [:new, :create]
  before_action :current_user, except: [:new, :create]
  
  def index 
    @users = User.all
  end
  
  def new 
    @user = User.new
  end
  
  def create 
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user 
    else 
      flash[:errors] = @user.errors.full_messages
      #might need to recirect here and not render
      #to signup path
      render :new
    end
  end
  
  def show 
    @users = User.all
    @user = User.find(params[:id])
    @friends = @user.friends 
    @friendes = @user.friendes 
    @not_friending = @user.not_friends
    @review = Review.new
  end

  def edit
    @user = User.find(params[:id])
    # @user.avatar.attach(params[:avatar])
  end

  def add_friend 
    @user = User.find(params[:id])
    User.find_by(user_params).friends << @user
    redirect_to @user
  end

  def update 
    @user = User.find(params[:id])
   if  @user.update(user_params)
    redirect_to @user
   else
    render :edit
   end
  end

  

  def add_friend_profile
    @user = User.find(params[:id])
    @current_user.friendes << @user
    # @current_user.friends << @user  --- this adds current user as a friend to user which we dont neccesarily want
    redirect_to @user
  end

  
 #working on this now

  # def delete_friendship
  #   @user = User.find(params[:id])
  #   @current_user.friendes.destroy
  #   redirect_to current_user
  # end



  def destroy
    @current_user.destroy
    session[:user_id] = nil
    redirect_to '/homes/home_page'
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :age, :bio, :food_choice, :love_choice, :avatar, :password, :password_confirmation)
  end
  
end

frate/app/helpers/analytics_helper.rb
module AnalyticsHelper
end

frate/app/helpers/application_helper.rb
module ApplicationHelper
end

frate/app/helpers/login_pages_helper.rb
module LoginPagesHelper
end

frate/app/helpers/matches_helper.rb
module MatchesHelper
end

frate/app/helpers/users_helper.rb
module UsersHelper
end

frate/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
  
      <%= yield %>

  </body>
</html>

frate/app/views/reviews/index.html.erb
<!doctype html>
<html lang="en">

<head>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="css/style.css">


<link href="https://fonts.googleapis.com/css?family=Oswald&display=swap" rel="stylesheet">

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anon ymous">

        <style>

  .mainpage {
    font-family: 'Oswald', sans-serif;
    margin: auto;
    width: 95%;
    padding: 10px;
    position: relative;
  }

#frate {
  color: #ff0066;
  text-align: center;
  margin-top: -40px;
}

  h1 {
    font-size: 50px
  }

  #title {
    font-size: 4rem;
    text-align: center;
    color: #ff0066;
  }
  #photo_logo {
    margin-top: 25px;
  }

   .speech-bubble {
	position: relative;
	background: #ffe6e6;
  border-radius: .4em;
  width: 50%;
  margin-left: 20px;
  text-align: center;
  border-style: solid;
  border-color: #D3D3D3;
  padding: 1%;
}
.speech-bubble:after {
	content: '';
	position: absolute;
	left: 0;
	top: 50%;
	width: 0;
	height: 0;
	border: 20px solid transparent;
	border-right-color: #D3D3D3;
	border-left: 0;
	border-bottom: 0;
	margin-top: -10px;
	margin-left: -20px;
}
#buttonforp {
  margin-left: 20px;
  margin-bottom: 50px;
}

  </style>

    <title>Frate</title>
</head>
 
<body>


<div class="wrapper d-flex align-items-stretch">
			<nav id="sidebar">
        <div class="p-4 pt-5">
          <a href="#" class="img logo rounded-circle mb-5" style="background-image: url(https://us.123rf.com/450wm/arbuzu/arbuzu1607/arbuzu160700095/60765606-letter-f-heart-icon-design-template-elements.jpg?ver=6);"></a>
          <h3 id="frate">Frate</h3>

          <br>
                  <ul class="list-unstyled components mb-5">
                  <li>
                  <%= link_to("Home", analytics_path(@analytics), method: :get) %>
              </li>
              <li>
              <%= link_to("My Profile", current_user, method: :get) %>
          </li>
	          <li>
	              <%= link_to "All Users", users_path %>
            </li>
            <li>
              <a href="#">My Messages</a>
	          </li>
	          <li>
              <%= link_to "My Reviews", "/users/#{current_user.id}/reviews" %>
	          </li>
            <li>
            
                <%= link_to "Logout", {:controller=> 'sessions', :action=> "destroy"}, :method=> :delete%><br>
            </li>
           
	        </ul>

	      </div>
    	</nav>

        <!-- Page Content  -->
      <div id="content" >


      <h1 id="title"><img src="https://us.123rf.com/450wm/arbuzu/arbuzu1607/arbuzu160700095/60765606-letter-f-heart-icon-design-template-elements.jpg?ver=6"; width="80", height="80", class="img logo rounded-circle mb-5", id="photo_logo"> Reviews for <%= @user.name %> </h1>
      <br>


  <% @reviews.each do |r| %>
        <% if r.reviewee == @user  %>
        <br>
        <div class="speech-bubble">
        <%= r.content %><br>
        <em>by, <%=begin r.reviewer.name rescue 'User profile has been deleted' end%> </em><br>
        </div>
      </br>
    <% end %>
  <% end %>
    

<br>
<%= link_to("Go back to #{@user.name}'s Profile", user_path(@user), class: "btn btn-outline-danger btn-md", id: "buttonforp") %>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</body>

</html>

frate/app/views/reviews/new.html.erb
<h1>Reviews are written here</h1>
<%= form_for @review do |f| %>
<%= f.label :content %>
<%= f.text_area :content %>
<%= f.text_area :reviewee_id%>

<%= f.submit "Make a review" %>
<% end %>
<% end %>
<br>

frate/app/views/reviews/show.html.erb
<h1>Reviews For </h1>
<% @reviews.each do |r| %>
<%= r.content %>
<% end%>

frate/app/views/users/edit.html.erb
<!doctype html>
<html lang="en">

<head>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="css/style.css">


<link href="https://fonts.googleapis.com/css?family=Oswald&display=swap" rel="stylesheet">

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anon ymous">

        <style>

  .mainpage {
    font-family: 'Oswald', sans-serif;
    margin: auto;
    width: 95%;
    padding: 10px;
    position: relative;
  }

  #welcome {
    color: #F5F5F5;
    text-align: center;
    margin-top: 30px;
    font-weight: 300;
  }

  #frate {
    color: #ff0066;
    text-align: center;
    margin-top: -40px;
  }

  h1 {
    font-size: 50px
  }
  </style>

    <title>Frate</title>
</head>
 
<body>


<div class="wrapper d-flex align-items-stretch">
			<nav id="sidebar">
				<div class="p-4 pt-5">
		  		<a href="#" class="img logo rounded-circle mb-5" style="background-image: url(https://us.123rf.com/450wm/arbuzu/arbuzu1607/arbuzu160700095/60765606-letter-f-heart-icon-design-template-elements.jpg?ver=6);"></a>
          <h3 id="frate">Frate</h3>
          <h4 id="welcome">Hello <%= @current_user.name %> </h4>

          <br>
                  <ul class="list-unstyled components mb-5">
                  <li>
                  <%= link_to("Home", analytics_path(@analytics), method: :get) %>
              </li>
              <li>
              <%= link_to("My Profile", @current_user, method: :get) %>
          </li>
	          <li>
	              <%= link_to "All Users", users_path %>
            </li>
            <li>
              <a href="#">My Messages</a>
          </li>
	          <li>
              <a href="#">My Reviews</a>
	          </li>
            <li>
            <%= link_to("Logout", homes_path(@homes), method: :get) %>
             </li>
	        </ul>

	      </div>
    	</nav>

        <!-- Page Content  -->
      <div id="content" >


      <div class="mainpage">
<h1> Edit Your Profile </h1><br>
<%= form_for @user do |f| %>

<%= f.label :name %>: 
<%= f.text_field :name %><br>

<%= f.label :age %>:
<%= f.number_field :age %><br>

<%= f.label :bio %>:
<%= f.text_area :bio %><br>

<%= f.label :favourite_food %>:
<%= f.select :food_choice, options_for_select = {"Italian" => 1, "Chinese" => 2, "Mexican" => 3, "Thai" => 4, "Indian" => 5, "Japanese or Sushi" => 6, "Mediterranean" => 7, "Other" => 8}, :class => 'genForm_dropBox' %> </br>

<%= f.label :are_you_looking_for_love_or_friendship? %> Tick the box for Love:
<%= f.check_box :love_choice %> <br />

<%= f.label :profile_photo %>
<%= f.file_field :avatar %><br>

<br>
<%= f.submit "Update your Profile" %>
    <% end%>  

    <% if @user.errors.any? %>
  <ul>
    <% @user.errors.full_messages.each do |e| %>
      <li style="color:red;"><%= e %></li>
    <% end %>
  </ul>
<% end %>
</div>

<script src="sidebar-01/js/jquery.min.js"></script>
<script src="sidebar-01/js/popper.js"></script>
<script src="sidebar-01/js/bootstrap.min.js"></script>
<script src="sidebar-01/js/main.js"></script>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</body>

</html>

frate/app/views/users/show.html.erb
<!doctype html>
<html lang="en">

<head>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="css/style.css">


<link href="https://fonts.googleapis.com/css?family=Oswald&display=swap" rel="stylesheet">

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anon ymous">

        <style>

  .mainpage {
    font-family: 'Oswald', sans-serif;
    margin: auto;
    width: 95%;
    padding: 10px;
    position: relative;
  }

#frate {
  color: #ff0066;
  text-align: center;
  margin-top: -40px;
}

#buttons {
  display: flex;
  align-items: center;
  justify-content: center;
}

#welcome {
  color: #F5F5F5;
  text-align: center;
  margin-top: 30px;
  font-weight: 300;
}

#yourname {
  text-align: center;
  color: #ff0066;
}

#title {
    font-size: 80px;
    text-align: center;
    color: #ff0066;
  }
  #photo_logo {
    margin-top: 25px;
  }

  h1 {
    font-size: 50px
  }

  .userimage {
    display: flex;
  align-items: center;
  justify-content: center;
  }

  .column {
  float: left;
  width: 50%;
  display: block;
  
}

.row:after {
  content: "";
  display: table;
  clear: both;
}


#grids {
  display: grid;
  grid-template-columns: 1fr 1fr 1fr;
  grid-gap: 10px;
  text-align: center;
}

#others {
  width:33.333333%; 
  float:left;
}

#add_friend {
  display: flex;
  align-items: center;
  justify-content: center;
}


  </style>

    <title>Frate</title>
</head>
 
<body>


<div class="wrapper d-flex align-items-stretch">		<nav id="sidebar">
        <div class="p-4 pt-5">
          <a href="#" class="img logo rounded-circle mb-5" style="background-image: url(https://us.123rf.com/450wm/arbuzu/arbuzu1607/arbuzu160700095/60765606-letter-f-heart-icon-design-template-elements.jpg?ver=6);"></a>
          <h3 id="frate">Frate</h3>
          <h4 id="welcome">Hello <%= @current_user.name %> </h4>

          <br>
                  <ul class="list-unstyled components mb-5">
                  <li>
                  <%= link_to("Home", analytics_path(@analytics), method: :get) %>
              </li>
              <li>
              <%= link_to("My Profile", @current_user, method: :get) %>
          </li>
	          <li>
	              <%= link_to "All Users", users_path %>
            </li>
            <li>
              <a href="#">My Messages</a>
	          </li>
	          <li>
              <%= link_to "My Reviews", "/users/#{current_user.id}/reviews" %>             
	          </li>
            <li>
            <%= link_to "Logout", {:controller=> 'sessions', :action=> "destroy"}, :method=> :delete%><br>
             </li>
	        </ul>

	      </div>
    	</nav>		

        <!-- Page Content  -->
      <div id="content" >




      <div class="mainpage">
 <% if @current_user.id == params[:id].to_i%>
 <h1 id="title"><img src="https://us.123rf.com/450wm/arbuzu/arbuzu1607/arbuzu160700095/60765606-letter-f-heart-icon-design-template-elements.jpg?ver=6"; width="80", height="80", class="img logo rounded-circle mb-5", id="photo_logo"> Your Profile </h1>
<h2 id="yourname">- <%= @current_user.name %> -</h2> <br>
<div id="buttons">
<%= link_to("Edit Account", edit_user_path(@user), class: "btn btn-outline-dark",) %>
</div>
<br>
<br>


<% else %> 
<h1 id="title"><img src="https://us.123rf.com/450wm/arbuzu/arbuzu1607/arbuzu160700095/60765606-letter-f-heart-icon-design-template-elements.jpg?ver=6"; width="80", height="80", class="img logo rounded-circle mb-5", id="photo_logo"><%= @user.name %>'s Profile</h1>
  <% if @current_user != @user && current_user.friendes.exclude?(@user)  %>       
  <div id="add_friend" >
       <%= form_for @current_user, url: { action: "add_friend_profile" } do |f|  %>
        <%= f.hidden_field :name %>
      <%= f.submit "Add friend", class:"btn btn-outline-danger btn-lg" %>
        </div>
    <% end %>  
  <% end %>
<% end %>
<br>

<div id="add_friend" >
<% if @current_user.id != params[:id].to_i && @current_user.friendes.include?(@user) %>
<%= submit_tag "Delete friend", class:"btn btn-outline-danger btn-lg" %>
<% end %>
</div>
<br>



<div class="row">
  <div class="column">
  <% if @user.avatar.attached? %>
  <img src="<%= (url_for(@user.avatar)) %>"; width="90%", height="90%">
  <% end %>
  </div>
  <div class="column">
    <h3><strong>Age: </strong> <%= @user.age %> </h3>
    <br>
    <h3><strong>Bio: </strong> <%= @user.bio %></h3>
    <br>
  </div>
</div>
<br>
<br>
<br>
<br>


<div class="row">
<div class="column">
  <section id="gallery">
  <h2>  Matches: </h2>
  <br>
  <div class="container" id="grids">
  <% @users.each do |user| %>
    <% if user.love_choice == @user.love_choice %>
    <% if user.food_choice == @user.food_choice %>
      <% if @user != user %>
  <div class="row ">
      <div class="col s4 center">
           <div class="card">
                     <div class="card-body">
                    <h5 class="card-title"><%= user.name %></h5>
                    <%= link_to("Click Profile", user_path(user), method: :get, class: "btn btn-outline-danger btn-sm") %>
                </div>
               </div>
             </div>
           </div>
       <% end %>
       <% end%>
       <% end %>
       <% end %>
</div>
</section>
  </div>

  <div class="column">
  <section id="gallery">
  <h2> Friends:</h2><br>
  <br>
  <div class="container" id="grids">
  <% @user.friendes.each do |friend| %>
  <div class="row ">
      <div class="col s4 center">
           <div class="card">
                     <div class="card-body">
                    <h5 class="card-title"><%= friend.name %></h5>
                    <%= link_to("Click Profile", user_path(friend), method: :get, class: "btn btn-outline-danger btn-sm") %>
                </div>
               </div>
             </div>
           </div>
    
       <% end %>
</div>
</section>
</div>
</div>

<br>
<br>
  






<br> <!-- Make New Friends -->
<% if @current_user.id == params[:id].to_i%>
<h2>If you feel like we were wrong, make new friends here: </h2><br>
<% @not_friending.each do |user| %> 
 <% if user.id != @user.id %>    
 <div id="others">
   <ul>  
   <li>
   <%= (link_to user.name, user) %>
    <%= form_for user, url: { action: "add_friend" } do |f| %>
   <%= f.hidden_field :name %>
   <%= f.submit "Add friend" %>
    </li>
    </ul>
    </div>
  <% end %>  
 <% end %>
 <% end %>
<% end %>
<br>
<br>
<br>


<!-- Make Review -->
<% if @current_user.id != params[:id].to_i %>
    <h2>Leave a review for <%= @user.name %></h2>
    <%= link_to("See #{@user.name}'s Reviews", "/users/#{params[:id].to_i}/reviews", class: "btn btn-outline-danger btn-md",) %>
    <br>
  <br>
      <%= form_tag("/users/#{@user.id}/reviews") do %>
      <%= text_area_tag :content %>
  <br>
     <%= submit_tag "Enter", :class => "btn btn-outline-dark" %>
  <% end %>
<% end %>




<div class="row">
        <p> </p>
        <br>
        <p> </p>
</div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</body>

</html>